**Exercício 01**

Construa o operador linear diagonalizável $T:\mathbb{R}^3 \to \mathbb{R}^3$ que tenha $2$ e $9$ como autovalores de modo que os autoespaços sejam $V(2) = [(1,2,0),(0,6,1)]$ e $V(9) = [(1,1,1)]$.

In [1]:
import numpy as np

v1 = np.array([1, 2, 0])
v2 = np.array([0, 6, 1])
v3 = np.array([1, 1, 1])

P = np.column_stack([v1, v2, v3])

D = np.diag([2, 2, 9])

T_can = P @ D @ np.linalg.inv(P)

print("Matriz de T na base canônica:")
print(T_can)

print("\nVerificações:")
print("T(v1) =", T_can @ v1, "= 2 * v1 ?", np.allclose(T_can @ v1, 2*v1))
print("T(v2) =", T_can @ v2, "= 2 * v2 ?", np.allclose(T_can @ v2, 2*v2))
print("T(v3) =", T_can @ v3, "= 9 * v3 ?", np.allclose(T_can @ v3, 9*v3))

Matriz de T na base canônica:
[[ 4. -1.  6.]
 [ 2.  1.  6.]
 [ 2. -1.  8.]]

Verificações:
T(v1) = [2. 4. 0.] = 2 * v1 ? True
T(v2) = [ 0. 12.  2.] = 2 * v2 ? True
T(v3) = [9. 9. 9.] = 9 * v3 ? True


**Exercício 02**

Construa uma transformação linear que mapeia o vetor $\mathbf{v}=[1,1,1,1,1]\in\mathbb{R}^5$ nele mesmo, ou seja, a transformação deve satisfazer $\mathbf{A}\mathbf{v}=\mathbf{v}$.

In [2]:
import numpy as np

v = np.array([1, 1, 1, 1, 1])

# Matriz identidade 5x5
A = np.eye(5)

print("Matriz A (identidade):")
print(A)

print("\nVerificação A @ v = v:")
resultado = A @ v
print("A @ v =", resultado)
print("v =", v)
print("Iguais?", np.allclose(resultado, v))

Matriz A (identidade):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Verificação A @ v = v:
A @ v = [1. 1. 1. 1. 1.]
v = [1 1 1 1 1]
Iguais? True
